name: Git-secret Scan

on:
  push:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # Cloning git-secrets and installing it on runner
    - name: Install git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install
    
    # Using curl to fetch signatures and store them in a file.
    # Configuring provider
    - name: Configuring git-secrets
      run: |
        export URL=https://gist.githubusercontent.com/ayushpriya10/a5e24168c059487952cf5e531e3596aa/raw/9a41ead571921cb34b8e46695d19524723e26841/git-secrets-regex-signatures
        curl $URL > signatures
        cat signatures
        git secrets --add-provider -- cat signatures
        
    # Executing Scan
    - name: Executing Scan
      run: git secrets --scan
