# Renaming the workflow
name: Gitleaks Scan

on:
  push:
    branches: [ master ]

jobs:
  scan:
    # Switching to Ubuntu 18.04 as runner OS
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    # Installing Golang on Runner
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.2' # The Go version to download

    # Installing Gitleaks and executing scan
    - name: Running Gitleaks
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        GO111MODULE=on go get github.com/zricethezav/gitleaks
        gitleaks --repo-path `pwd` --verbose
